In [ ]:
!pip install qiskit

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 36.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 57.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 54.5/54.5 kB 3.5 MB/s eta 0:00:00


Primeiro vamos criar nosso ket0 que representa o estado de um vetor/QBIT

Podemos ver a parte imáginaria + 0.j

In [ ]:
from qiskit.quantum_info import Statevector
import numpy as np

# Criando um vetor

ket0 = Statevector([1, 0])
ket0

Statevector([1.+0.j, 0.+0.j],
            dims=(2,))


In [ ]:
# Print normal do vetor
print(ket0.data) # [1+0.j 0+0.j]

[1.+0.j 0.+0.j]


In [ ]:
# Se estiver em um Jupyter, podemos desenhar o vetor
ket0.draw() # por padrão, escreve o estado em ASCII
ket0.draw('latex') # desenha o vetor em LaTeX

<IPython.core.display.Latex object>

In [ ]:
# Checa se o vetor é válido
print(ket0.is_valid()) # True

True


##Modificando um estado

Agora vamos criar um portão ou vetor X para multriplicar e mudar a amplitude de possibilidade quantica do nosso estado do QBIT

In [ ]:
X = np.array([[0, 1], [1, 0]])
X

array([[0, 1],
       [1, 0]])

Aqui estamos pegando nosso estado de vetor ket0 e passando como um array para manipular

In [ ]:
ket0 = np.array([1, 0])
ket0

array([1, 0])

Usando o np.dot estamos multiplicando o vetor ket0 pelo X e salvando em um ket1, gerando um novo vetor

In [ ]:
ket1 = np.dot(X, ket0)
ket1

array([0, 1])

Aqui podemos ver o resultado junto com a parte imaginaria

In [ ]:
ket1_state = Statevector(ket1)
ket1_state

Statevector([0.+0.j, 1.+0.j],
            dims=(2,))


In [ ]:
print(ket1_state.data) # [0.+0.j 1+0.j]
print(ket1_state.is_valid()) # True

[0.+0.j 1.+0.j]
True


Existem diversos portões/operações que podemos realizar X, Y, Z, Adamar


O portão Adamar é muito importante, pois ele cria a super-posição, probabilidade de ser 0 ou 1

#Medindo um Estado

In [ ]:
ket0 = np.array([1, 0])
ket_p = Statevector((1/np.sqrt(2))*np.array([1,1]))

print(ket_p) # [0.70710678+0.j 0.70710678+0.j]

# Calculando manualmente a probabilidade de medir zero
prob = np.abs(ket_p.inner(ket0))**2
print(prob) # 0.4999999999999999

# Calculando todas as probabilidades automaticamente
prob = ket_p.probabilities() # [0.5 0.5]
print(prob[0]) # 0.4999999999999999

Statevector([0.70710678+0.j, 0.70710678+0.j],
            dims=(2,))
0.4999999999999999
0.4999999999999999


#Visualização com a Esfera de Bloch

In [ ]:
import matplotlib.pyplot as plt
from qiskit.quantum_info import Statevector
from qiskit.visualization import plot_bloch_multivector

ket0 = Statevector([1, 0])
ket1 = Statevector([0, 1])


#Criando e visualizando estados aleatórios

In [ ]:
import numpy as np
import random as rd
import matplotlib.pyplot as plt
from qiskit.quantum_info import Statevector
from qiskit.visualization import plot_bloch_multivector

theta = rd.uniform(0, np.pi)
phi   = rd.uniform(0, 2*np.pi)

alpha = np.cos(theta/2)
beta  = np.exp(phi*1.j)*np.sin(theta/2)

ket_psi = Statevector([alpha, beta])

plot_bloch_multivector(ket_psi, title='Estado psi')
plt.show()